app:
  environment: "prod"

logger:
  level: "info"

database:
  host: "postgres"
  port: 5082
  username: "postgres"
  password: "password"
  name: "wakarimi_files_db"

http:
  host: "localhost"
  port: 8080