basePath: /api
definitions:
  dir_handler.trackRequest:
    properties:
      path:
        description: Path to the directory on disk
        type: string
    type: object
  dir_handler.trackResponse:
    properties:
      dirId:
        description: Unique identifier of the directory in the database
        type: integer
      name:
        description: Name of the directory
        type: string
    type: object
  responses.Error:
    properties:
      message:
        type: string
      reason:
        type: string
    type: object
host: localhost:8022
info:
  contact:
    email: zalimannard@mail.ru
    name: Dmitry Kolesnikov (Zalimannard)
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Wakarimi Music Files API
  version: "0.4"
paths:
  /dirs:
    post:
      consumes:
      - application/json
      description: Adds a new directory to the database for tracking
      parameters:
      - description: Directory Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dir_handler.trackRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dir_handler.trackResponse'
        "400":
          description: Failed to decode request
          schema:
            $ref: '#/definitions/responses.Error'
        "404":
          description: Directory not found
          schema:
            $ref: '#/definitions/responses.Error'
        "409":
          description: Directory already tracked
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Add a new tracked directory
      tags:
      - Directories
swagger: "2.0"
